---
abstract: 'API to Fogbugz XML webservice'
author:
  - 'Gareth Kirwan <gbjk@thermeon.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-FogBugz-XML
version: 1.0000
