---
abstract: 'API to Fogbugz XML webservice'
author:
  - 'Gareth Kirwan <gbjk@thermeon.com>'
build_requires:
  Term::ReadKey: 0
  Test::More: 0
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-FogBugz-XML
requires:
  Config::Any: 0
  Data::Dumper: 0
  HTTP::Request: 0
  IO::Prompt: 0
  LWP::UserAgent: 0
  Moose: 0
  XML::LibXML: 0
  common::sense: 0
  namespace::autoclean: 0
  perl: v5.10.0
resources:
  repository: git://github.com/gbjk/webservice-fogbugz-xml.git
version: 1.0001
